### PR TITLE
Rename HSL to Digitransit, use v2 API

### PR DESCRIPTION
**Pull request by tpikonen**
I noticed the HSL map source did not work any more, so I upgraded the it to use the v2 API and added support for API keys, which are now (possibly, see below) needed.

I also renamed the source to Digitransit, since that's the organization which hands out the keys.

This seems to work also without API keys, at least somewhat. When using an API key I still get 401 errors in the debug logs, but only in high zoom levels, which I also get without an API key.

### CODE REVIEW

**Comment by tpikonen** [comment]
The map dict is missing the `keys` key, which causes the API key to be not sent. The API key is only needed for the really high zoom levels though, so I'm not sure if we want to use it at all.

**Comment by tpikonen** [comment]
Digitransit also has a vector map, which could work with something like this:

```
{
  "attribution": {
    "Digitransit": "https://digitransit.fi/",
    "© OpenStreetMap": "https://www.openstreetmap.org/copyright"
  },
  "name": "Digitransit vector",
  "format": "mapbox-gl",
  "fingerprint": {},
  "keys": ["DIGITRANSIT_KEY"],
  "style_url": "https://raw.githubusercontent.com/HSLdevcom/hsl-map-style/master/style/hsl-map-style-base.json",
  "url_suffix": "?digitransit-subscription-key=#DIGITRANSIT_KEY#",
  "lang": { "local": "text", "int": "text_en", "fi": "text", "en": "text_en", "sv": "text_sv" },
  "profiles": ["mixed", "online"],
  "provider": "Digitransit vector",
  "light": "day",
  "type": "default"
}
```

The API key does not seem to be substituted to `url_suffix`, and when I add it manually, it apparently does not get added to vector tile downloads, so this does not work. I have a really old version of maplibre-native-qt here though, which may have something to do with the latter problem.

**Comment by rinigus** [comment]
Thank you for working on it!

> The map dict is missing the keys key, which causes the API key to be not sent. The API key is only needed for the really high zoom levels though, so I'm not sure if we want to use it at all.

you mean that digitransit.json is missing `keys` list, right?

Re vector maps: It seems that this style [https://raw.githubusercontent.com/HSLdevcom/hsl-map-style/master/style/hsl-map-style-base.json] is missing few elements: sprite and glyphs, for example. I guess they generate it on fly based on the styles in that repository. So, we would need a JSON with full spec there.

As for why urlSuffix is failing, try to set [urlDebug](https://github.com/rinigus/mapbox-gl-qml/blob/master/api.md#mangling-of-urls) in Map.qml of Pure Maps. I suspect that it is trying to pull JSON with the suffix as well. But would be good to check it.

**Comment by tpikonen** [comment]
The raster maps seem to work fine without an API key, so I removed it here.

> you mean that digitransit.json is missing keys list, right?

Yes.

> Re vector maps: It seems that this style is missing few elements

True, the full style is here: https://raw.githubusercontent.com/HSLdevcom/hsl-map-style/master/style.json

I'll make a separate PR for the vector maps, but... It's complicated.

> As for why urlSuffix is failing, try to set urlDebug in Map.qml

Thanks, this was what I was missing for debugging this, but was too lazy to find out myself :)

**Comment by rinigus** [comment]
Thank you very much!

**Pull request merged**
