### PR TITLE
Package Flite with Ubuntu Touch click

### PR DESCRIPTION
**Pull request by jonnius**
This builds and ships flite with the Ubuntu Touch package.

# Issues
- Click package with Flite is 23 MB in size

### CODE REVIEW

**Comment by rinigus** [comment]
sounds like these other `flite_xxx` files are voices. what's the file sizes for them? maybe flite contains all voices and the rest just one? if its true, we can remove all other flite_* siblings

what should we do now with mimic? do we drop that PR? there is a permissions suggestion from dev channel chat, please take a look on that.

**Comment by rinigus** [comment]
PS: if we ship with flite, we don't need mimic. if you want to go for better voice, we need mimic, but not flite. in general, I think flite is OK. personally, I use mimic though. you could test on PC with flite voices and mimic's ap voice

flite voices selection at https://github.com/rinigus/pure-maps/blob/master/poor/voice.py#L125

for mimic: https://github.com/rinigus/pure-maps/blob/master/poor/voice.py#L152

**Comment by jonnius** [comment]
I have asked in UBports QA group what they think about the size-quality-tradeoff. Adding just the voices we really use reduced the package size by another 10 MB :)

**Comment by jonnius** [comment]
Closing this as we want to go with Mimic

**Pull request closed without merging**
