### PR TITLE
Rename installed data files to use a DBus well-known name

### PR DESCRIPTION
**Pull request by pabloyoyoista**
Alternative solution to #594 

The logic behind is that data files like appstream data and desktop files should have a valid DBus well-known name: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id I am unfortunately not acquainted with all the differences in packaging for the different systems, but I this seems to build and work well in linux.

### CODE REVIEW

**Comment by rinigus** [comment]
It is not clear to me what such split to APP_NAME and APP_REV_NAME would achieve?

**Comment by pabloyoyoista** [comment]
Sorry I wasn't super clear about it. So #594 tried to solve the problem that in regular distribution installations, the desktop file referenced by the metainfo file doesn't exist. It had to be reverted because flatpak build would fail. Looking at the problem a bit in more detail, I found:
 - According to specification, the desktop file should be static, ideally follow the "reverse DNS" convention an be a well-known name.
 - Current packaging modifies that name of the desktop file based on a build-time option.
 
 Therefore, I thought that the right solution would be to make sure (by hard-coding) that the desktop file always remain compliant with the specification. Additionally, there are other assets, like icons and the metainfo file, which in my mind made sense to always install based on a well-known name. Although I would have no problem reverting those back.

Why not change the default of APP_NAME instead? Looking at the code, it seems to me that there is a good reason for the APP_NAME (and therefore the executable) to be customized based on a build-time option. However, my understanding is that regular installations through some package manager would not expect executables to be installed following a "reverse DNS" convention and that it made sense to split it into `APP_NAME` and `APP_REV_NAME`.

Sorry I didn't provide these explanations before!

**Comment by rinigus** [comment]
I must say I am reluctant to make changes in the build system. We would have then to check it against

- Sailfish
- Ubuntu Touch
- postmarketOS
- Flatpak

I will trigger Flatpak build and report back on the result.

**Comment by pabloyoyoista** [comment]
Yes, I understand the burden. I built it using pmbootstrap. So I would consider at least the pmOS also checked.

**Comment by rinigus** [comment]
Great, thanks for checking! Flatpak is fine as well.

I will merge it and I hope it will work for SFOS and UT too

**Comment by pabloyoyoista** [comment]
Thanks a lot! Let me know if there are any issues and I'll try my best :)

**Comment by rinigus** [comment]
There are some expectations for SFOS, those I think I fixed in a1d5dcf5fc720a1d809facd646ccd7941607cf01 . Hopefully, they will also fix builds for UT

/cc @jonnius - see commit a1d5dcf5fc720a1d809facd646ccd7941607cf01

**Comment by jonnius** [comment]
Just tested it on UT. Works fine. Thanks for covering UT.

**Pull request merged**
