### PR TITLE
Package Mimic with Ubuntu Touch Package

### PR DESCRIPTION
**Pull request by jonnius**
This builds and ships mimic with the Ubuntu Touch package.

# Issues
- Building mimic takes 45min on my (rather old) machine
- Click package with mimic is 85 MB in size

### CODE REVIEW

**Comment by rinigus** [comment]
I think we need mimic only, rest can be removed.

If the size is such an issue, maybe we need to package flite instead

**Comment by jonnius** [comment]
Stripping mimic and removing unecessary binaries click size is reduced to 82 MB at least.

**Comment by jonnius** [comment]
Is it this flite? https://github.com/festvox/flite

**Comment by rinigus** [comment]
yeah, should be

**Comment by rinigus** [comment]
From UT Dev Group regarding permissions for playing audio:

```
ah i see what's wrong. the `pure-maps.apparmor` needs to have `"template": "ubuntu-sdk"` added in
```

**Comment by rinigus** [comment]
PS: thanks for helping with it!

**Comment by jonnius** [comment]
I'll give it a try

**Comment by jonnius** [comment]
Unfortunately the template tweak didn't help.

**Comment by rinigus** [comment]
Yeah, I can see in the dev channel. I'll be traveling tomorrow, probably will be offline for 24h or more.

**Comment by rinigus** [comment]
should we consider mimic PR ready-for-merge?

**Comment by jonnius** [comment]
Yes :+1:

**Comment by rinigus** [comment]
Let me fix dark icons first, then will merge and rerun build

**Comment by rinigus** [comment]
Thanks!

**Pull request merged**
