### PR TITLE
Switch Clickable config to QMake

### PR DESCRIPTION
**Pull request by jonnius**
see #423

### CODE REVIEW

**Comment by jonnius** [comment]
@rinigus, I run into
```
QQmlApplicationEngine failed to load component
file://share/pure-maps/qml/pure-maps.qml:-1 No such file or directory
```

The paths would need to be relative to the cwd from which the app is started (also stored in `APP_DIR` at runtime). With the old `make` approach I would simply set `PREFIX` to literaly `.` and that worked. But QMake seems to directly replace the `.` by the cwd at build time. Any idea how to fix this?

**Comment by rinigus** [comment]
Looks like we used `PREFIX` and `PREFIX_RUNNING` in OSM Scout Server for it. I have added now this separation to Pure Maps as well. Try to use `PREFIX=/usr` and `PREFIX_RUNNING=usr` here too. You would have to rebase to the current qmake branch though - to get the last commit.

**Comment by jonnius** [comment]
Oh, I forgot about the issue with OSM Scout Server. Using `PREFIX_RUNNING` solves it.

Now I run into this (in Clickable Desktop Mode):
```
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"/home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/poor/__init__.py\", line 42, in <module>\n    from poor import util\n\n  File \"/home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/poor/util.py\", line 24, in <module>\n    import gpxpy.parser\n\nImportError: No module named 'gpxpy'\n"
qml: Error: Cannot import module: poor (Traceback (most recent call last):

  File "/home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/poor/__init__.py", line 42, in <module>
    from poor import util

  File "/home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/poor/util.py", line 24, in <module>
    import gpxpy.parser

ImportError: No module named 'gpxpy'
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'poor' is not defined\n"
qml: Error: Function not found: 'poor.main' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'poor' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'poor' is not defined\n"
qml: Error: Function not found: 'poor.conf.get_all' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'poor' is not defined
)
file:///home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/qml/Config.qml:165: TypeError: Cannot read property 'auto_complete_geo' of undefined
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'poor' is not defined\n"
qml: Error: Function not found: 'poor.conf.get_all' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'poor' is not defined
)
file:///home/jonatan/entwicklung/pure-maps/build/x86_64-linux-gnu/app/install/share/pure-maps.jonnius/qml/Config.qml:165: TypeError: Cannot read property 'auto_complete_geo' of undefined
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
Failed to set Geoclue positioning requirements. Geoclue error: org.qtproject.QtDBus.Error.InvalidObjectPath
```
The `poor` directory looks basically as before, thought. Only major differences I see between this build and the one with make is:
- `share/pure-maps.jonnius/thirdparty/gpxpy` is missing
- `share/pure-maps.jonnius/icons` is missing

**Comment by rinigus** [comment]
Re icons: yes, this is expected. They are all under qml/icons now

Re gpxpy: Use `CONFIG+=install_gpxpy` (not CONFIGS) in the build script. That should fix it.

**Comment by jonnius** [comment]
Yes, we are close. It already works in Clickable Desktop Mode now after fixing the typo.

I am afraid we still need to distinguish app name and full app name. Otherwise we will not be able to publish it as the same app to the Open Store to provide existing users with updates. And it would not even start at the device as it is configured now. I could not figure out how to create a manifest getting along having the maintainer name already in the app name.

**Comment by rinigus** [comment]
If we have to have 2 names then that is doable. It seems to me that OSM Scout Server did not require it, though. 

With the respect of full and short names, what should be done regarding it? What's the name of exe file? Where should it be installed?

**Comment by jonnius** [comment]
The reason why the OSM Scout Server works without that separation is that it runs unconfined. If we ever wanted to make it confined, we would need to change that as well. It would not be a bad idea to change it anyway to conform to the UT standard paths.

- The exec typically is the app name (but we could put anything in the desktop file). To avoid specifying a path to it in the desktop file, it should be in `PATH`, which includes `$PREFIX_RUNNING/bin` and `$PREFIX_RUNNING/lib/<architecture_triplet>/bin`.
- In the manifest we need to set the full name at the name field and a hook for the app name (where we reference the desktop and apparmor files).
- The [paths accessible](docs.ubports.com/en/latest/appdev/guides/writeable-dirs.html) by a confined app use the full name as `APPNAME` (to avoid clashes between apps of same name but different maintainers).

**Comment by rinigus** [comment]
What is not clear whether we could just set whole application as `pure-maps.jonnius` as APP_NAME. That would make it automatically to use all required paths and should function properly. It is such a mess otherwise to handle two names and make separation between APP_NAME and FULL_NAME.

If you want to keep `pure-maps` as executable, we can also add that handling in packaging script. Namely, we can:

- compile with `qmake APP_NAME=pure-maps.jonnius`
- `make install`
- `mv usr/bin/pure-maps.jonnius usr/bin/pure-maps`

That will internally configure Pure Maps to use ~/.config/pure-maps.jonnius/... (as well as other paths) and should make it compliant to Ubuntu Touch requirements, if I understand it correctly.

**Comment by jonnius** [comment]
Seems I was wrong about `./bin` being in `PATH`. After moving the binary to the other location it works again. Setting the full name as `APP_NAME` works fine.

**Comment by jonnius** [comment]
I did not set the temp dir differently, yet. What do I need to do with the app to see if there is an issue with that?

**Comment by rinigus** [comment]
> I did not set the temp dir differently, yet. What do I need to do with the app to see if there is an issue with that?

it is used for sound file generation. So, in Preferences/Testing, just play test sound

**Comment by jonnius** [comment]
Now everything seems to work fine.

**Comment by rinigus** [comment]
But slim version maybe has a different name?

**Comment by jonnius** [comment]
Fixed the slim build as well. Should be ready to merge.

**Comment by rinigus** [comment]
Thank you very much, merged!

**Pull request merged**
