### PR TITLE
cmake: Add find_package() call for S2

### PR DESCRIPTION
**Pull request by tpikonen**
This fixes build failure with s2geometry 0.11.1.

### CODE REVIEW

**Comment by rinigus** [comment]
I will merge this without testing, just will not be able to do so during next few weeks. If something breaks, we can fix it later. Thank you very much!

**Comment by jonnius** [comment]
@rinigus, the click build currently uses your [packaging repo](https://github.com/rinigus/s2geometry) of s2geometry which does not export the [targets like upstream](https://github.com/google/s2geometry/blob/master/CMakeLists.txt#L467) that are needed to be compatible with this change.

Could you upgrade the version in your packaging repository to have it included or is there a reason we can't do that? Should we cherry-pick / backport the necessary CMake change? Or could I just switch to the upstream project for click packaging?

**Comment by rinigus** [comment]
sorry for late reply. please switch to upstream - I will probably do the same for SFOS

**Comment by jonnius** [comment]
Just be aware that you'll need abseil, too. And if you build it from sources, you'll need [this patch](https://git.openembedded.org/meta-openembedded/plain/meta-oe/recipes-devtools/abseil-cpp/abseil-cpp/0002-Remove-maes-option-from-cross-compilation.patch) for cross-compiling due to [this issue](https://github.com/abseil/abseil-cpp/issues/1241).

**Comment by rinigus** [comment]
Thank you for the tips!

**Pull request merged**
