### PR TITLE
Package PicoTTS with Ubuntu Touch Package

### PR DESCRIPTION
**Pull request by jonnius**
This builds and ships picotts with the Ubuntu Touch package.

# Issues
- Click package with mimic is 8 MB in size

### CODE REVIEW

**Comment by jonnius** [comment]
@rinigus where do I actually need to put the language files? What I got now is `usr/share/picotts/lang/` inside the app. Thats the path that works for me on desktop. But it seems like it is waiting for the wav file like forever: [error.log](https://github.com/rinigus/pure-maps/files/3538163/error.log)

**Comment by rinigus** [comment]
I guess this pico2wave is crashing. I don't know where should we put language files and whether we can somehow specify path. Should probably read the source and figure out from it :(

**Comment by rinigus** [comment]
PS: Long WAV waiting means it didn't manage to generate it

**Comment by jonnius** [comment]
Ok, I figgured it out. Thanks for you hints.

**Comment by rinigus** [comment]
is it ready for merging now?

**Comment by jonnius** [comment]
Yep

**Comment by rinigus** [comment]
just merged mimic => conflicts are there

**Comment by jonnius** [comment]
Conflicts are solved.

**Pull request merged**
