### PR TITLE
brought svgs opacity on equal levels and refactored profile icons

### PR DESCRIPTION
**Pull request by eLtMosen**

### CODE REVIEW

**Comment by eLtMosen** [comment]
No idea about 47065a1... It is the merge when i updated my fork from your master to be on same level before doing 5dd4838 changes. Did i do something wrong?

**Comment by rinigus** [comment]
No worries, I'll merge them. Its probably due to the parallel changes that we did.

**Comment by rinigus** [comment]
PS: Thanks a lot!

**Comment by eLtMosen** [comment]
Don't thank me to early. Actually i am a noob to SW development as you can see in forgetting halv the stuff and doing another PR 515eebc right after :)
So, thank you for your patience and competent maintainer-ship.

**Comment by rinigus** [comment]
NP, we all start somewhere :)

**Pull request merged**
