### PR TITLE
[WIP] QtCreator support

### PR DESCRIPTION
**Pull request by accumulator**
This PR is not ready for merge, just to discuss!

Two project files are created
- sailfish/harbour-pure-maps.pro
- desktop/pure-maps.pro

Both .pro files include /common.pri, which includes the common QML and contains a qmake representation of most of the (current) Makefile targets. Notable exception is the rpm-sailfish target, which is a bit of a PITA to get working from both the SDK and without the SDK using qmake -> generated Makefile -> make rpm-sailfish

Platform specific QML has been moved into target folders sailfish/qml/platform and desktop/qml/platform

Building from the SDK currently generates a valid sailfish RPM, with a few deviations:
    - gettext and Qt linguist translations not included yet
    - sailfish app launcher icons still in original place (in /data. Do we want to share app launcher icons between Sailfish and generic QtQuickControls build?), and are not in the place the SDK expects them. Locally I have them moved, but I haven't committed them.
    - .svg files from qml/icons are added in packaging (ok? or want to exclude?)
    - svg2png executables are included (move to tools?)
    - various README.md's in the tree not included (however this is correct I think, as it contains notice to developers)

The desktop project is not tested yet (I need to prep all dependencies on my Debian), it only shows all relevant files in the project.

You can generate a Makefile and check if the same targets you're used to are present by issuing a 

`
QMAKEFEATURES=. qmake
`

in the sailfish directory

Still TODO to get feature parity:
- translations
- add flatpak target to desktop .pro file
- add rpm-sailfish target to sailfish .pro file in a way that doesn't conflict with building in SDK

### CODE REVIEW

**Comment by rinigus** [comment]
I am sorry to say, but I think these changes are too extensive and don't really bring advantages. 

Personally, I think the only issue we are missing in terms of PRO files is simplicity of editing. In this aspect, we could even merge all platforms into a single PRO file and use `make` and `qmlscene` for all other operations (rpm, flatpak and testing).

Maybe I should create such simplistic PRO file?

**Comment by accumulator** [comment]
Sorry to hear that.. I don't think these are very extensive changes, basically only QML files have been moved and .pro files have been added.

Did you try the Makefile it generated?

**Comment by rinigus** [comment]
On desktop:

```
> qmake ../desktop/pure-maps.pro
> make
g++ -Wl,-O1 -o pure-maps    -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:229: pure-maps] Error 1
```

But the main problem is that this PR tries to fix something which is not broken. At least for me, and as far as I remember for Osmo as well, the development runs via rsync on device and running `qmlscene`. I would like to keep it this way. Especially now, when I don't even need to develop at SFOS at all - I do all my initial tests and development using desktop version using `qmlscene`. For that, this PR breaks it all.

The main issue was editing the files and for that we don't even need any specific targets nor split into platform-specific PROs even. We have RPM generation that works excellent and doesn't require any SFOS specific code. I am creating SFOS RPMs directly from my desktop Linux - something I could not enjoy earlier with OSM Scout Server. Its so much easier and faster that I don't want to change it either.

I do admit that it will be better to have QtCreator for QML editing, but for that, PRO file which will just include all the sources and will not care about installation will be fine.

Please don't get discouraged with this and I am sorry for not thinking it fully through when you initially proposed it. Your help and input is very much welcome and appreciated.

**Comment by rinigus** [comment]
I can see that you closed up all pull requests and this issue. Which is unfortunate and I am sorry about it.

**Pull request closed without merging**
